name: hready
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  shared_preferences: ^2.2.0
  lottie: ^3.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/primary.png"

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Poppins Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf